name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: true
      comment_id:
        required: true
      job:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:    
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status

    steps:
      - uses: actions/checkout@v4
      - name: digger run
        uses: diggerhq/digger@v0.4.1
        with:
          setup-aws: true
          aws-role-to-assume: 'arn:aws:iam::891377204276:role/github-oidc'
          aws-region: us-east-1
          digger-hostname: 'https://cloud.digger.dev'
          digger-organisation: 'digger-playground'
          digger-token: ${{ secrets.DIGGER_TOKEN }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
         